const Permissions = {
  CrearLeads: "Crear Leads",
  ModificarLeads: "Modificar Leads",
  EliminarLeads: "Eliminar Leads",
  VendedoresCrear: "Crear Vendedores",
  VendedoresModificar: "Modificar Vendedores",
  VendedoresEliminar: "Eliminar Vendedores",
  CoordinadoresCrear: "Crear Coordinadores",
  CoordinadoresEditar: "Editar Coordinadores",
  CoordinadoresEliminar: "Eliminar Coordinadores",
  OficinasCrear: "Crear Oficinas",
  OficinasEditar: "Editar Oficinas",
  OficinasEliminar: "Eliminar Oficinas",
  SubirArchivosPromocion: "Subir archivos de promoción",
  AsignarLeadsPorOficina: "Asignar leads por oficina",
  AsignarLeadsPorVendedor: "Asignar leads por vendedor",
  UsuariosCRUD: "CRUD de usuarios",
  CrearUsuarios: "Crear usuarios",
  ModificarUsuarios: "Modificar usuarios",
  EliminarUsuarios: "Eliminar usuarios",
  ModificarPermisos: "Modificar permisos",
  Usuarios: "Usuarios",
  Oficinas: "Oficinas",
  Archivos: "Archivos",
  SinAsignacion: "Sin Asignación",
};

export default Permissions;
