export const Ciudades = [
    {
        "Estado": "Aguascalientes",
        "Ciudad": [
            "Tepezal\u00e1",
            "Aguascalientes",
            "Rinc\u00f3n de Romos",
            "El Llano",
            "Pabell\u00f3n de Arteaga",
            "Jes\u00fas Mar\u00eda",
            "Asientos",
            "San Jos\u00e9 de Gracia",
            "San Francisco de los Romo",
            "Calvillo",
            "Cos\u00edo"
        ]
    },
    {
        "Estado": "Baja_California",
        "Ciudad": [
            "Tecate",
            "San Felipe",
            "Tijuana",
            "Mexicali",
            "Playas de Rosarito",
            "San Quint\u00edn",
            "Ensenada"
        ]
    },
    {
        "Estado": "Baja_California_Sur",
        "Ciudad": [
            "Los Cabos",
            "Muleg\u00e9",
            "La Paz",
            "Loreto",
            "Comond\u00fa"
        ]
    },
    {
        "Estado": "Campeche",
        "Ciudad": [
            "Tenabo",
            "Calkin\u00ed",
            "Hecelchak\u00e1n",
            "Dzitbalch\u00e9",
            "Campeche",
            "Hopelch\u00e9n",
            "Calakmul",
            "Palizada",
            "Esc\u00e1rcega",
            "Candelaria",
            "Carmen",
            "Seybaplaya",
            "Champot\u00f3n"
        ]
    },
    {
        "Estado": "Coahuila_de_Zaragoza",
        "Ciudad": [
            "Arteaga",
            "Sierra Mojada",
            "Casta\u00f1os",
            "Nava",
            "Matamoros",
            "San Buenaventura",
            "Viesca",
            "General Cepeda",
            "Lamadrid",
            "Candela",
            "Progreso",
            "Ocampo",
            "Guerrero",
            "Hidalgo",
            "Parras",
            "Escobedo",
            "Abasolo",
            "Allende",
            "Monclova",
            "Sacramento",
            "Torre\u00f3n",
            "Frontera",
            "Nadadores",
            "Morelos",
            "Piedras Negras",
            "Ramos Arizpe",
            "San Pedro",
            "Jim\u00e9nez",
            "Cuatro Ci\u00e9negas",
            "Sabinas",
            "San Juan de Sabinas",
            "Acu\u00f1a",
            "Francisco I. Madero",
            "Ju\u00e1rez",
            "Zaragoza",
            "Villa Uni\u00f3n",
            "Saltillo",
            "M\u00fazquiz"
        ]
    },
    {
        "Estado": "Colima",
        "Ciudad": [
            "Colima",
            "Manzanillo",
            "Ixtlahuac\u00e1n",
            "Cuauht\u00e9moc",
            "Tecom\u00e1n",
            "Coquimatl\u00e1n",
            "Villa de \u00c1lvarez",
            "Armer\u00eda",
            "Comala",
            "Minatitl\u00e1n"
        ]
    },
    {
        "Estado": "Chiapas",
        "Ciudad": [
            "Berrioz\u00e1bal",
            "Mazapa de Madero",
            "El Parral",
            "Copainal\u00e1",
            "Metapa",
            "Catazaj\u00e1",
            "Siltepec",
            "Altamirano",
            "Tenejapa",
            "Osumacinta",
            "Soyal\u00f3",
            "Benem\u00e9rito de las Am\u00e9ricas",
            "San Juan Cancuc",
            "Tzimol",
            "La Independencia",
            "Sital\u00e1",
            "Escuintla",
            "Maravilla Tenejapa",
            "Chenalh\u00f3",
            "Aldama",
            "Pichucalco",
            "Tuxtla Guti\u00e9rrez",
            "Larr\u00e1inzar",
            "Motozintla",
            "Oxchuc",
            "Pijijiapan",
            "Pantelh\u00f3",
            "Arriaga",
            "Pantepec",
            "Amatenango del Valle",
            "La Trinitaria",
            "La Concordia",
            "Ixtacomit\u00e1n",
            "Mazat\u00e1n",
            "Amat\u00e1n",
            "Bella Vista",
            "Tapilula",
            "Ixhuat\u00e1n",
            "La Libertad",
            "Socoltenango",
            "Chiapa de Corzo",
            "Ocotepec",
            "Ixtapa",
            "Teopisca",
            "Tapalapa",
            "Ostuac\u00e1n",
            "La Grandeza",
            "El Porvenir",
            "Huitiup\u00e1n",
            "Sabanilla",
            "Chamula",
            "Yajal\u00f3n",
            "Chicoas\u00e9n",
            "Chicomuselo",
            "Frontera Comalapa",
            "Ray\u00f3n",
            "Huixt\u00e1n",
            "Palenque",
            "\u00c1ngel Albino Corzo",
            "Huixtla",
            "Venustiano Carranza",
            "San Andr\u00e9s Duraznal",
            "Suchiate",
            "Reforma",
            "Cacahoat\u00e1n",
            "Francisco Le\u00f3n",
            "Mapastepec",
            "Acapetahua",
            "Ocosingo",
            "Tecpat\u00e1n",
            "Ixtapangajoya",
            "Jitotol",
            "Chil\u00f3n",
            "Bejucal de Ocampo",
            "Sunuapa",
            "Honduras de la Sierra",
            "Ocozocoautla de Espinosa",
            "San Crist\u00f3bal de las Casas",
            "Capit\u00e1n Luis \u00c1ngel Vidal",
            "Mitontic",
            "Acacoyagua",
            "Tuxtla Chico",
            "San Lucas",
            "Amatenango de la Frontera",
            "Mezcalapa",
            "Emiliano Zapata",
            "Tapachula",
            "Salto de Agua",
            "Suchiapa",
            "Huehuet\u00e1n",
            "Zinacant\u00e1n",
            "Villaflores",
            "Frontera Hidalgo",
            "Solosuchiapa",
            "Simojovel",
            "Bochil",
            "Coapilla",
            "Marqu\u00e9s de Comillas",
            "Las Rosas",
            "Montecristo de Guerrero",
            "Rinc\u00f3n Chamula San Pedro",
            "Nicol\u00e1s Ru\u00edz",
            "Jiquipilas",
            "Cintalapa de Figueroa",
            "San Fernando",
            "Uni\u00f3n Ju\u00e1rez",
            "Santiago el Pinar",
            "Chalchihuit\u00e1n",
            "Tila",
            "Tumbal\u00e1",
            "Villa Corzo",
            "Chapultenango",
            "Acala",
            "Tuzant\u00e1n",
            "Las Margaritas",
            "Pueblo Nuevo Solistahuac\u00e1n",
            "Chanal",
            "Totolapa",
            "Ju\u00e1rez",
            "Villa Comaltitl\u00e1n",
            "Tonal\u00e1",
            "El Bosque",
            "Comit\u00e1n de Dom\u00ednguez",
            "Chiapilla"
        ]
    },
    {
        "Estado": "Chihuahua",
        "Ciudad": [
            "Coyame del Sotol",
            "El Tule",
            "Guadalupe",
            "Manuel Benavides",
            "Moris",
            "Carich\u00ed",
            "Guazapares",
            "Praxedis G. Guerrero",
            "Matamoros",
            "Dr. Belisario Dom\u00ednguez",
            "Bach\u00edniva",
            "San Francisco del Oro",
            "San Francisco de Conchos",
            "Julimes",
            "Riva Palacio",
            "Balleza",
            "Bocoyna",
            "Aquiles Serd\u00e1n",
            "Ascensi\u00f3n",
            "Meoqui",
            "Ocampo",
            "Guerrero",
            "Satev\u00f3",
            "Camargo",
            "Hidalgo del Parral",
            "Santa B\u00e1rbara",
            "Galeana",
            "Rosario",
            "Uruachi",
            "Allende",
            "Coronado",
            "Matach\u00ed",
            "Aldama",
            "Rosales",
            "G\u00f3mez Far\u00edas",
            "Delicias",
            "Maguarichi",
            "Buenaventura",
            "Urique",
            "La Cruz",
            "Ahumada",
            "Guachochi",
            "Ch\u00ednipas",
            "Cusihuiriachi",
            "Ojinaga",
            "Namiquipa",
            "San Francisco de Borja",
            "Nonoava",
            "Morelos",
            "Gran Morelos",
            "Valle de Zaragoza",
            "L\u00f3pez",
            "Jim\u00e9nez",
            "Cuauht\u00e9moc",
            "Casas Grandes",
            "Madera",
            "Batopilas de Manuel G\u00f3mez Mor\u00edn",
            "Tem\u00f3sachic",
            "Nuevo Casas Grandes",
            "Ju\u00e1rez",
            "Janos",
            "Saucillo",
            "Guadalupe y Calvo",
            "Ignacio Zaragoza",
            "Santa Isabel",
            "Huejotit\u00e1n",
            "Chihuahua"
        ]
    },
    {
        "Estado": "Ciudad de M\u00e9xico",
        "Ciudad": [
            "Cuauht\u00e9moc",
            "Iztacalco",
            "Benito Ju\u00e1rez",
            "Tl\u00e1huac",
            "Gustavo A. Madero",
            "Coyoac\u00e1n",
            "Venustiano Carranza",
            "\u00c1lvaro Obreg\u00f3n",
            "Cuajimalpa de Morelos",
            "Iztapalapa",
            "La Magdalena Contreras",
            "Milpa Alta",
            "Tlalpan",
            "Xochimilco",
            "Miguel Hidalgo",
            "Azcapotzalco"
        ]
    },
    {
        "Estado": "Durango",
        "Ciudad": [
            "Santa Clara",
            "G\u00f3mez Palacio",
            "Lerdo",
            "Pueblo Nuevo",
            "Poanas",
            "Rodeo",
            "Nazas",
            "Cuencam\u00e9",
            "Tlahualilo",
            "San Juan de Guadalupe",
            "Mapim\u00ed",
            "Coneto de Comonfort",
            "S\u00fachil",
            "General Sim\u00f3n Bol\u00edvar",
            "Tepehuanes",
            "San Dimas",
            "Ocampo",
            "Hidalgo",
            "Ot\u00e1ez",
            "San Luis del Cordero",
            "Durango",
            "Topia",
            "Mezquital",
            "Guanacev\u00ed",
            "P\u00e1nuco de Coronado",
            "Nuevo Ideal",
            "Santiago Papasquiaro",
            "El Oro",
            "San Pedro del Gallo",
            "Nombre de Dios",
            "Ind\u00e9",
            "Canelas",
            "San Juan del R\u00edo",
            "Vicente Guerrero",
            "Pe\u00f1\u00f3n Blanco",
            "San Bernardo",
            "Canatl\u00e1n",
            "Tamazula",
            "Guadalupe Victoria"
        ]
    },
    {
        "Estado": "Guanajuato",
        "Ciudad": [
            "Tierra Blanca",
            "Villagr\u00e1n",
            "Atarjea",
            "San Diego de la Uni\u00f3n",
            "Jer\u00e9cuaro",
            "Ac\u00e1mbaro",
            "Pueblo Nuevo",
            "Dolores Hidalgo Cuna de la Independencia Nacional",
            "Victoria",
            "Manuel Doblado",
            "Coroneo",
            "Salvatierra",
            "San Jos\u00e9 Iturbide",
            "Le\u00f3n",
            "Uriangato",
            "Salamanca",
            "Jaral del Progreso",
            "Doctor Mora",
            "Ocampo",
            "Valle de Santiago",
            "Apaseo el Alto",
            "San Francisco del Rinc\u00f3n",
            "Silao de la Victoria",
            "Abasolo",
            "Pur\u00edsima del Rinc\u00f3n",
            "Guanajuato",
            "San Luis de la Paz",
            "Irapuato",
            "Cortazar",
            "San Felipe",
            "Santa Cruz de Juventino Rosas",
            "Comonfort",
            "Huan\u00edmaro",
            "Cuer\u00e1maro",
            "Morole\u00f3n",
            "Xich\u00fa",
            "P\u00e9njamo",
            "Celaya",
            "Apaseo el Grande",
            "Tarimoro",
            "Tarandacuao",
            "Santiago Maravat\u00edo",
            "San Miguel de Allende",
            "Romita",
            "Santa Catarina",
            "Yuriria"
        ]
    },
    {
        "Estado": "Guerrero",
        "Ciudad": [
            "Tecoanapa",
            "Benito Ju\u00e1rez",
            "General Canuto A. Neri",
            "Tlapehuala",
            "Tepecoacuilco de Trujano",
            "Pedro Ascencio Alquisiras",
            "Ayutla de los Libres",
            "Las Vigas",
            "Santa Cruz del Rinc\u00f3n",
            "Atenango del R\u00edo",
            "Atoyac de \u00c1lvarez",
            "Xalpatl\u00e1huac",
            "San Miguel Totolapan",
            "Quechultenango",
            "Igualapa",
            "Mochitl\u00e1n",
            "Copala",
            "Alcozauca de Guerrero",
            "Taxco de Alarc\u00f3n",
            "Cuautepec",
            "Zapotitl\u00e1n Tablas",
            "Coahuayutla de Jos\u00e9 Mar\u00eda Izazaga",
            "Ajuchitl\u00e1n del Progreso",
            "Tlapa de Comonfort",
            "Alpoyeca",
            "Juan R. Escudero",
            "Tlalixtaquilla de Maldonado",
            "Cutzamala de Pinz\u00f3n",
            "San Nicol\u00e1s",
            "Azoy\u00fa",
            "Pilcaya",
            "Tlacoapa",
            "Acapulco de Ju\u00e1rez",
            "Tixtla de Guerrero",
            "Apaxtla",
            "Juchit\u00e1n",
            "Iguala de la Independencia",
            "Cocula",
            "Leonardo Bravo",
            "Eduardo Neri",
            "Acatepec",
            "Zitlala",
            "Ahuacuotzingo",
            "Cual\u00e1c",
            "Jos\u00e9 Joaqu\u00edn de Herrera",
            "Buenavista de Cu\u00e9llar",
            "Florencio Villarreal",
            "Chilapa de \u00c1lvarez",
            "Pungarabato",
            "Olinal\u00e1",
            "Petatl\u00e1n",
            "T\u00e9cpan de Galeana",
            "Atlixtac",
            "Coyuca de Ben\u00edtez",
            "Coyuca de Catal\u00e1n",
            "San Luis Acatl\u00e1n",
            "Cochoapa el Grande",
            "Marquelia",
            "Xochistlahuaca",
            "General Heliodoro Castillo",
            "La Uni\u00f3n de Isidoro Montes de Oca",
            "Arcelia",
            "Ometepec",
            "Cuetzala del Progreso",
            "Copanatoyac",
            "Copalillo",
            "San Marcos",
            "Zihuatanejo de Azueta",
            "Huitzuco de los Figueroa",
            "Teloloapan",
            "Tlalchapa",
            "Tlacoachistlahuaca",
            "Xochihuehuetl\u00e1n",
            "Zir\u00e1ndaro",
            "M\u00e1rtir de Cuilapan",
            "Cuajinicuilapa",
            "Huamuxtitl\u00e1n",
            "Atlamajalcingo del Monte",
            "Iliatenco",
            "Metlat\u00f3noc",
            "Ixcateopan de Cuauht\u00e9moc",
            "Chilpancingo de los Bravo",
            "Malinaltepec",
            "\u00d1uu Savi",
            "Tetipac"
        ]
    },
    {
        "Estado": "Hidalgo",
        "Ciudad": [
            "Metztitl\u00e1n",
            "Omitl\u00e1n de Ju\u00e1rez",
            "Chapantongo",
            "Chilcuautla",
            "Tlaxcoapan",
            "Progreso de Obreg\u00f3n",
            "Lolotla",
            "Jacala de Ledezma",
            "Actopan",
            "Yahualica",
            "Zapotl\u00e1n de Ju\u00e1rez",
            "Mineral del Monte",
            "Tepeji del R\u00edo de Ocampo",
            "Tenango de Doria",
            "Eloxochitl\u00e1n",
            "Chapulhuac\u00e1n",
            "Jaltoc\u00e1n",
            "Ju\u00e1rez Hidalgo",
            "Pacula",
            "Atlapexco",
            "El Arenal",
            "Villa de Tezontepec",
            "Zacualtip\u00e1n de \u00c1ngeles",
            "Tecozautla",
            "Huichapan",
            "Tetepango",
            "Acaxochitl\u00e1n",
            "Huejutla de Reyes",
            "San Agust\u00edn Metzquititl\u00e1n",
            "Apan",
            "Tepetitl\u00e1n",
            "Santiago Tulantepec de Lugo Guerrero",
            "Ixmiquilpan",
            "Pachuca de Soto",
            "Tlahuelilpan",
            "Tula de Allende",
            "Tlanchinol",
            "Nicol\u00e1s Flores",
            "Cuautepec de Hinojosa",
            "Almoloya",
            "Tepeapulco",
            "Huehuetla",
            "Molango de Escamilla",
            "Calnali",
            "Atitalaquia",
            "Tepehuac\u00e1n de Guerrero",
            "Mineral del Chico",
            "Tlahuiltepa",
            "Tlanalapa",
            "Huasca de Ocampo",
            "Atotonilco de Tula",
            "Tianguistengo",
            "Emiliano Zapata",
            "Zempoala",
            "San Bartolo Tutotepec",
            "San Felipe Orizatl\u00e1n",
            "La Misi\u00f3n",
            "Cardonal",
            "Francisco I. Madero",
            "Tizayuca",
            "Nopala de Villagr\u00e1n",
            "Epazoyucan",
            "Mixquiahuala de Ju\u00e1rez",
            "Metepec",
            "Tulancingo de Bravo",
            "Santiago de Anaya",
            "Tasquillo",
            "Xochiatipan",
            "Tezontepec de Aldama",
            "Huautla",
            "San Salvador",
            "Acatl\u00e1n",
            "Agua Blanca de Iturbide",
            "Atotonilco el Grande",
            "Zimap\u00e1n",
            "Pisaflores",
            "Mineral de la Reforma",
            "Huazalingo",
            "San Agust\u00edn Tlaxiaca",
            "Ajacuba",
            "Xochicoatl\u00e1n",
            "Alfajayucan",
            "Tolcayuca",
            "Singuilucan"
        ]
    },
    {
        "Estado": "Jalisco",
        "Ciudad": [
            "San Ignacio Cerro Gordo",
            "Cuautitl\u00e1n de Garc\u00eda Barrag\u00e1n",
            "Villa Corona",
            "El Lim\u00f3n",
            "Guadalajara",
            "Amatit\u00e1n",
            "Teocuitatl\u00e1n de Corona",
            "Poncitl\u00e1n",
            "San Diego de Alejandr\u00eda",
            "Acatl\u00e1n de Ju\u00e1rez",
            "Tuxpan",
            "Atoyac",
            "Jamay",
            "Cihuatl\u00e1n",
            "Colotl\u00e1n",
            "Concepci\u00f3n de Buenos Aires",
            "Zapotitl\u00e1n de Vadillo",
            "Encarnaci\u00f3n de D\u00edaz",
            "G\u00f3mez Far\u00edas",
            "Bola\u00f1os",
            "San Sebasti\u00e1n del Oeste",
            "Tecolotl\u00e1n",
            "Guachinango",
            "El Grullo",
            "Tapalpa",
            "Juanacatl\u00e1n",
            "Tenamaxtl\u00e1n",
            "Chapala",
            "Cuqu\u00edo",
            "Ayutla",
            "Atotonilco el Alto",
            "Zapopan",
            "Ayotl\u00e1n",
            "Villa Hidalgo",
            "Jocotepec",
            "Chiquilistl\u00e1n",
            "San Juanito de Escobedo",
            "El Arenal",
            "Atenguillo",
            "Zapotlanejo",
            "Yahualica de Gonz\u00e1lez Gallo",
            "La Barca",
            "Santa Mar\u00eda del Oro",
            "Tonaya",
            "Atemajac de Brizuela",
            "San Juan de los Lagos",
            "Ixtlahuac\u00e1n del R\u00edo",
            "Mascota",
            "Magdalena",
            "Zapotiltic",
            "Hostotipaquillo",
            "La Huerta",
            "Ameca",
            "Jes\u00fas Mar\u00eda",
            "Cabo Corrientes",
            "Sayula",
            "Cocula",
            "Tototl\u00e1n",
            "Zapotl\u00e1n el Grande",
            "Etzatl\u00e1n",
            "Ixtlahuac\u00e1n de los Membrillos",
            "Mazamitla",
            "San Miguel el Alto",
            "Valle de Ju\u00e1rez",
            "Tuxcacuesco",
            "Tamazula de Gordiano",
            "Villa Purificaci\u00f3n",
            "Autl\u00e1n de Navarro",
            "La Manzanilla de la Paz",
            "San Gabriel",
            "Juchitl\u00e1n",
            "Ocotl\u00e1n",
            "Degollado",
            "Casimiro Castillo",
            "Villa Guerrero",
            "Arandas",
            "Atengo",
            "San Mart\u00edn Hidalgo",
            "Quitupan",
            "San Mart\u00edn de Bola\u00f1os",
            "Uni\u00f3n de San Antonio",
            "Ahualulco de Mercado",
            "Jalostotitl\u00e1n",
            "Valle de Guadalupe",
            "Tonila",
            "Puerto Vallarta",
            "Mixtl\u00e1n",
            "Totatiche",
            "Huej\u00facar",
            "San Pedro Tlaquepaque",
            "Amacueca",
            "San Marcos",
            "Tizap\u00e1n el Alto",
            "Uni\u00f3n de Tula",
            "Tala",
            "Teuchitl\u00e1n",
            "Tlajomulco de Z\u00fa\u00f1iga",
            "Tecalitl\u00e1n",
            "Ejutla",
            "San Juli\u00e1n",
            "Ca\u00f1adas de Obreg\u00f3n",
            "Techaluta de Montenegro",
            "Tuxcueca",
            "Talpa de Allende",
            "El Salto",
            "San Crist\u00f3bal de la Barranca",
            "Santa Mar\u00eda de los \u00c1ngeles",
            "Mezquitic",
            "Tequila",
            "Teocaltiche",
            "Pihuamo",
            "Tepatitl\u00e1n de Morelos",
            "Cuautla",
            "Tolim\u00e1n",
            "Zacoalco de Torres",
            "Acatic",
            "Chimaltit\u00e1n",
            "Jilotl\u00e1n de los Dolores",
            "Zapotl\u00e1n del Rey",
            "Huejuquilla el Alto",
            "Mexticac\u00e1n",
            "Tonal\u00e1",
            "Ojuelos de Jalisco",
            "Lagos de Moreno",
            "Tomatl\u00e1n"
        ]
    },
    {
        "Estado": "M\u00e9xico",
        "Ciudad": [
            "Mexicaltzingo",
            "Aculco",
            "Jilotzingo",
            "Jaltenco",
            "San Mart\u00edn de las Pir\u00e1mides",
            "Tepetlaoxtoc",
            "Lerma",
            "Tenango del Aire",
            "Xalatlaco",
            "Coacalco de Berrioz\u00e1bal",
            "Cuautitl\u00e1n Izcalli",
            "Texcalyacac",
            "San Mateo Atenco",
            "Temamatla",
            "Almoloya del R\u00edo",
            "Valle de Chalco Solidaridad",
            "Otzoloapan",
            "Jilotepec",
            "Hueypoxtla",
            "La Paz",
            "Tec\u00e1mac",
            "Chapultepec",
            "Papalotla",
            "Villa Victoria",
            "Zacazonapan",
            "Tultitl\u00e1n",
            "Cocotitl\u00e1n",
            "Chalco",
            "Jiquipilco",
            "Polotitl\u00e1n",
            "Timilpan",
            "Ixtlahuaca",
            "Tejupilco",
            "Tlalnepantla de Baz",
            "Atlacomulco",
            "Teotihuac\u00e1n",
            "Atlautla",
            "Tenancingo",
            "Amanalco",
            "Ixtapaluca",
            "Tonatico",
            "Sultepec",
            "Villa del Carb\u00f3n",
            "Tezoyuca",
            "Tlatlaya",
            "Chiautla",
            "Malinalco",
            "Ray\u00f3n",
            "Melchor Ocampo",
            "Zinacantepec",
            "Chimalhuac\u00e1n",
            "Texcaltitl\u00e1n",
            "San Antonio la Isla",
            "Tenango del Valle",
            "Atenco",
            "Tepotzotl\u00e1n",
            "Nextlalpan",
            "El Oro",
            "Zumpango",
            "Huehuetoca",
            "Valle de Bravo",
            "Ayapango",
            "Chapa de Mota",
            "Ocoyoacac",
            "Nopaltepec",
            "Coatepec Harinas",
            "Isidro Fabela",
            "Ozumba",
            "Amecameca",
            "Ecatepec de Morelos",
            "Cuautitl\u00e1n",
            "Ixtapan de la Sal",
            "Tianguistenco",
            "Chiconcuac",
            "Villa Guerrero",
            "Apaxco",
            "Capulhuac",
            "Tlalmanalco",
            "Amatepec",
            "Santo Tom\u00e1s",
            "Juchitepec",
            "Almoloya de Alquisiras",
            "Soyaniquilpan de Ju\u00e1rez",
            "Zacualpan",
            "Temascalapa",
            "Ocuilan",
            "Almoloya de Ju\u00e1rez",
            "Otzolotepec",
            "Chicoloapan",
            "Acambay de Ru\u00edz Casta\u00f1eda",
            "Toluca",
            "Ixtapan del Oro",
            "Metepec",
            "Luvianos",
            "Zumpahuac\u00e1n",
            "Temascaltepec",
            "Villa de Allende",
            "Coyotepec",
            "Tepetlixpa",
            "Huixquilucan",
            "Ecatzingo",
            "Tultepec",
            "Atizap\u00e1n de Zaragoza",
            "San Jos\u00e9 del Rinc\u00f3n",
            "Jocotitl\u00e1n",
            "Naucalpan de Ju\u00e1rez",
            "Temoaya",
            "Axapusco",
            "Donato Guerra",
            "Tonanitla",
            "San Felipe del Progreso",
            "Nezahualc\u00f3yotl",
            "Acolman",
            "Nicol\u00e1s Romero",
            "Joquicingo",
            "Calimaya",
            "Morelos",
            "Temascalcingo",
            "Xonacatl\u00e1n",
            "San Sim\u00f3n de Guerrero",
            "Texcoco",
            "Atizap\u00e1n",
            "Otumba",
            "Tequixquiac",
            "Teoloyucan"
        ]
    },
    {
        "Estado": "Michoac\u00e1n_de_Ocampo",
        "Ciudad": [
            "Tanhuato",
            "Tangamandapio",
            "Coalcom\u00e1n de V\u00e1zquez Pallares",
            "Panind\u00edcuaro",
            "Ixtl\u00e1n",
            "Sahuayo",
            "L\u00e1zaro C\u00e1rdenas",
            "Acuitzio",
            "Charo",
            "Tuxpan",
            "Marcos Castellanos",
            "Ecuandureo",
            "Churintzio",
            "Aguililla",
            "Ario",
            "Cuitzeo",
            "Buenavista",
            "Tingambato",
            "Ting\u00fcind\u00edn",
            "Tumbiscat\u00edo",
            "Los Reyes",
            "Uruapan",
            "Aporo",
            "Chilchota",
            "La Piedad",
            "Susupuato",
            "Coeneo",
            "Puru\u00e1ndiro",
            "Huandacareo",
            "Tac\u00e1mbaro",
            "Tzitzio",
            "Morelia",
            "Zit\u00e1cuaro",
            "Quiroga",
            "Jos\u00e9 Sixto Verduzco",
            "Irimbo",
            "Aquila",
            "Par\u00e1cuaro",
            "Ocampo",
            "Hidalgo",
            "Tiquicheo de Nicol\u00e1s Romero",
            "Madero",
            "Tocumbo",
            "Venustiano Carranza",
            "Tlalpujahua",
            "Paracho",
            "Tanc\u00edtaro",
            "Tzintzuntzan",
            "Taretan",
            "Charapan",
            "Villamar",
            "Tlazazalca",
            "Ziracuaretiro",
            "M\u00fagica",
            "Jiquilpan",
            "Jungapeo",
            "Santa Ana Maya",
            "Angamacutiro",
            "Cotija",
            "Nahuatzen",
            "Epitacio Huerta",
            "Perib\u00e1n",
            "Nocup\u00e9taro",
            "Churumuco",
            "Angangueo",
            "San Lucas",
            "Nuevo Urecho",
            "Huaniqueo",
            "Tepalcatepec",
            "P\u00e1tzcuaro",
            "Brise\u00f1as",
            "Car\u00e1cuaro",
            "Jacona",
            "Tuzantla",
            "Contepec",
            "Jim\u00e9nez",
            "Zin\u00e1paro",
            "Penjamillo",
            "Lagunillas",
            "Cojumatl\u00e1n de R\u00e9gules",
            "La Huacana",
            "Salvador Escalante",
            "Chinicuila",
            "Arteaga",
            "Erongar\u00edcuaro",
            "Quer\u00e9ndaro",
            "\u00c1lvaro Obreg\u00f3n",
            "Gabriel Zamora",
            "Senguio",
            "Huetamo",
            "Vista Hermosa",
            "Cher\u00e1n",
            "Pur\u00e9pero",
            "Tar\u00edmbaro",
            "Zacapu",
            "Huiramba",
            "Turicato",
            "Numar\u00e1n",
            "Chuc\u00e1ndiro",
            "Coahuayana",
            "Maravat\u00edo",
            "Morelos",
            "Zamora",
            "Tanganc\u00edcuaro",
            "Ju\u00e1rez",
            "Nuevo Parangaricutiro",
            "Apatzing\u00e1n",
            "Zinap\u00e9cuaro",
            "Pajacuar\u00e1n",
            "Chavinda",
            "Cop\u00e1ndaro",
            "Yur\u00e9cuaro",
            "Indaparapeo"
        ]
    },
    {
        "Estado": "Morelos",
        "Ciudad": [
            "Temoac",
            "Zacatepec",
            "Xoxocotla",
            "Cuernavaca",
            "Tlalnepantla",
            "Tetela del Volc\u00e1n",
            "Mazatepec",
            "Axochiapan",
            "Hueyapan",
            "Ocuituco",
            "Puente de Ixtla",
            "Tetecala",
            "Miacatl\u00e1n",
            "Coatl\u00e1n del R\u00edo",
            "Jonacatepec de Leandro Valle",
            "Tlaltizap\u00e1n de Zapata",
            "Jojutla",
            "Yautepec",
            "Jantetelco",
            "Amacuzac",
            "Huitzilac",
            "Totolapan",
            "Tepoztl\u00e1n",
            "Emiliano Zapata",
            "Zacualpan de Amilpas",
            "Cuautla",
            "Jiutepec",
            "Temixco",
            "Coatetelco",
            "Tepalcingo",
            "Ayala",
            "Yecapixtla",
            "Tlaquiltenango",
            "Xochitepec",
            "Tlayacapan",
            "Atlatlahucan"
        ]
    },
    {
        "Estado": "Nayarit",
        "Ciudad": [
            "Ixtl\u00e1n del R\u00edo",
            "Del Nayar",
            "Rosamorada",
            "Ahuacatl\u00e1n",
            "Tuxpan",
            "Compostela",
            "Acaponeta",
            "Santa Mar\u00eda del Oro",
            "La Yesca",
            "Tecuala",
            "Amatl\u00e1n de Ca\u00f1as",
            "Jala",
            "Bah\u00eda de Banderas",
            "Santiago Ixcuintla",
            "Xalisco",
            "Tepic",
            "San Pedro Lagunillas",
            "Ru\u00edz",
            "San Blas",
            "Huajicori"
        ]
    },
    {
        "Estado": "Nuevo_Le\u00f3n",
        "Ciudad": [
            "Sabinas Hidalgo",
            "Salinas Victoria",
            "General Ter\u00e1n",
            "Guadalupe",
            "Cadereyta Jim\u00e9nez",
            "Monterrey",
            "Lampazos de Naranjo",
            "Agualeguas",
            "El Carmen",
            "General Bravo",
            "Linares",
            "Los Ramones",
            "Villaldama",
            "General Zuazua",
            "Pesquer\u00eda",
            "Mar\u00edn",
            "China",
            "Mina",
            "Hidalgo",
            "Garc\u00eda",
            "Vallecillo",
            "Galeana",
            "Iturbide",
            "General Escobedo",
            "Abasolo",
            "Par\u00e1s",
            "Montemorelos",
            "Bustamante",
            "An\u00e1huac",
            "Cerralvo",
            "Allende",
            "Doctor Arroyo",
            "General Trevi\u00f1o",
            "Melchor Ocampo",
            "Rayones",
            "Los Aldamas",
            "Mier y Noriega",
            "Doctor Coss",
            "San Pedro Garza Garc\u00eda",
            "Apodaca",
            "Santiago",
            "Aramberri",
            "Los Herreras",
            "Hualahuises",
            "Higueras",
            "Ju\u00e1rez",
            "General Zaragoza",
            "Doctor Gonz\u00e1lez",
            "San Nicol\u00e1s de los Garza",
            "Santa Catarina",
            "Ci\u00e9nega de Flores"
        ]
    },
    {
        "Estado": "Oaxaca",
        "Ciudad": [
            "Magdalena Mixtepec",
            "Santa Catarina Minas",
            "Chalcatongo de Hidalgo",
            "Uni\u00f3n Hidalgo",
            "San Jacinto Tlacotepec",
            "San Pedro Mixtepec -Dto. 22 -",
            "San Miguel Peras",
            "San Antonino Castillo Velasco",
            "San Mart\u00edn Zacatepec",
            "San Ildefonso Amatl\u00e1n",
            "San Juan Chicomez\u00fachil",
            "San Mateo R\u00edo Hondo",
            "San Juan Sayultepec",
            "La Trinidad Vista Hermosa",
            "Capul\u00e1lpam de M\u00e9ndez",
            "San Pedro Molinos",
            "Santa Luc\u00eda Monteverde",
            "San Juan Teitipac",
            "Santa Mar\u00eda Tataltepec",
            "Santa Mar\u00eda Huatulco",
            "San Andr\u00e9s Zautla",
            "San Juan Bautista Guelache",
            "San Pedro Sochi\u00e1pam",
            "San Juan Lalana",
            "San Gabriel Mixtepec",
            "San Bartolom\u00e9 Yucua\u00f1e",
            "Santa Cruz Acatepec",
            "Santiago Zacatepec",
            "San Sebasti\u00e1n Coatl\u00e1n",
            "San Pedro Ocopetatillo",
            "San Juan Yae\u00e9",
            "Santiago Textitl\u00e1n",
            "San Dionisio Ocotepec",
            "San Juan Bautista Atatlahuca",
            "Santa Catarina Lachatao",
            "Abejones",
            "Pluma Hidalgo",
            "Cosoltepec",
            "Ixtl\u00e1n de Ju\u00e1rez",
            "San Andr\u00e9s Huay\u00e1pam",
            "Santo Domingo Petapa",
            "Santiago Amoltepec",
            "Yutanduchi de Guerrero",
            "San Francisco Ozolotepec",
            "San Marcos Arteaga",
            "Huautla de Jim\u00e9nez",
            "Santa Mar\u00eda del Rosario",
            "San Pedro y San Pablo Ayutla",
            "San Antonio Nanahuat\u00edpam",
            "San Juan de los Cu\u00e9s",
            "Santiago Juxtlahuaca",
            "Santo Domingo Tomaltepec",
            "Santiago Tetepec",
            "Ciudad Ixtepec",
            "Nejapa de Madero",
            "San Agust\u00edn Atenango",
            "Santo Domingo Yanhuitl\u00e1n",
            "Rojas de Cuauht\u00e9moc",
            "San Sebasti\u00e1n Teitipac",
            "San Pablo Cuatro Venados",
            "San Juan del R\u00edo",
            "Santiago Yucuyachi",
            "Santa Cruz Nundaco",
            "Santiago Ixtayutla",
            "Santa Catarina Tayata",
            "Santa Cruz Xitla",
            "Santos Reyes Tepejillo",
            "San Sebasti\u00e1n Abasolo",
            "Oaxaca de Ju\u00e1rez",
            "Santo Tom\u00e1s Jalieza",
            "San Juan Tepeuxila",
            "San Pedro Ocotepec",
            "San Juan Bautista Coixtlahuaca",
            "San Antonio Huitepec",
            "Santiago Yaitepec",
            "San Crist\u00f3bal Lachirioag",
            "Monjas",
            "San Baltazar Loxicha",
            "Santa Mar\u00eda Yucuhiti",
            "San Lorenzo Cacaotepec",
            "San Miguel Tecomatl\u00e1n",
            "Coicoy\u00e1n de las Flores",
            "San Crist\u00f3bal Amatl\u00e1n",
            "Tepelmeme Villa de Morelos",
            "San Francisco Nuxa\u00f1o",
            "San Pedro M\u00e1rtir Yucuxaco",
            "San Juan Ozolotepec",
            "San Francisco Jaltepetongo",
            "San Antonio Acutla",
            "Santiago Comaltepec",
            "Santiago Yolom\u00e9catl",
            "San Bernardo Mixtepec",
            "Santa Cruz Mixtepec",
            "Santa Mar\u00eda Mixtequilla",
            "Santiago Pinotepa Nacional",
            "Villa Talea de Castro",
            "San Jos\u00e9 Ayuquila",
            "San Antonio Tepetlapa",
            "San Miguel Panixtlahuaca",
            "San Andr\u00e9s Zabache",
            "Magdalena Pe\u00f1asco",
            "San Juan Tamazola",
            "Santiago Astata",
            "San Pedro M\u00e1rtir",
            "San Miguel Achiutla",
            "Santa Mar\u00eda Tlahuitoltepec",
            "San Bartolom\u00e9 Quialana",
            "Teococuilco de Marcos P\u00e9rez",
            "San Juan Quiotepec",
            "Santiago Lalopa",
            "San Ildefonso Sola",
            "Santa Cruz Amilpas",
            "Santos Reyes Nopala",
            "Santa Ana del Valle",
            "San Lorenzo Texmel\u00facan",
            "San Mart\u00edn Tilcajete",
            "San Francisco Telixtlahuaca",
            "San Jer\u00f3nimo Silacayoapilla",
            "Santiago del R\u00edo",
            "Santa In\u00e9s Yatzeche",
            "San Juan Petlapa",
            "San Bartolo Coyotepec",
            "Teotongo",
            "Reyes Etla",
            "Santa Luc\u00eda del Camino",
            "Mat\u00edas Romero Avenda\u00f1o",
            "Santiago Apoala",
            "Santa Mar\u00eda del Tule",
            "San Mart\u00edn Huamel\u00falpam",
            "Santa Ana Cuauht\u00e9moc",
            "San Miguel Ejutla",
            "San Lucas Ojitl\u00e1n",
            "San Pedro Topiltepec",
            "San Marcial Ozolotepec",
            "Guadalupe de Ram\u00edrez",
            "San Pedro Nopala",
            "Santa Mar\u00eda Ipalapa",
            "Santa Ana",
            "Ixpantepec Nieves",
            "San Juan Guichicovi",
            "Santiago Camotl\u00e1n",
            "San Juan del Estado",
            "San Francisco Cajonos",
            "Santiago Miltepec",
            "San Melchor Betaza",
            "San Vicente Lachix\u00edo",
            "Santiago Laxopa",
            "Zapotitl\u00e1n Lagunas",
            "San Miguel Suchixtepec",
            "San Andr\u00e9s Huaxpaltepec",
            "San Andr\u00e9s Solaga",
            "Santiago Yaveo",
            "Santiago Llano Grande",
            "San Miguel Piedras",
            "Acatl\u00e1n de P\u00e9rez Figueroa",
            "San Juan Bautista Cuicatl\u00e1n",
            "Santa Mar\u00eda Ozolotepec",
            "San Jer\u00f3nimo Tlacochahuaya",
            "San Pedro Tida\u00e1",
            "San Miguel Chicahua",
            "San Juan Lajarcia",
            "Santa Cruz Tacache de Mina",
            "Santa Mar\u00eda Sola",
            "Santo Domingo Teojomulco",
            "San Crist\u00f3bal Suchixtlahuaca",
            "Heroica Ciudad de Ejutla de Crespo",
            "M\u00e1rtires de Tacubaya",
            "San Jos\u00e9 Independencia",
            "Santo Domingo Tonal\u00e1",
            "Salina Cruz",
            "Chiquihuitl\u00e1n de Benito Ju\u00e1rez",
            "Santiago Minas",
            "San Lucas Camotl\u00e1n",
            "San Francisco Teopan",
            "Tamazul\u00e1pam del Esp\u00edritu Santo",
            "San Miguel Tlacamama",
            "San Bartolo Yautepec",
            "San Carlos Yautepec",
            "Santa Mar\u00eda Tepantlali",
            "Santa Mar\u00eda Chilchotla",
            "San Lucas Quiavin\u00ed",
            "San Felipe Tejal\u00e1pam",
            "San Esteban Atatlahuca",
            "San Juan Comaltepec",
            "La Compa\u00f1\u00eda",
            "Santiago Zoochila",
            "Juchit\u00e1n de Zaragoza",
            "Santa Magdalena Jicotl\u00e1n",
            "Villa de Chilapa de D\u00edaz",
            "Tataltepec de Vald\u00e9s",
            "Santiago Nundiche",
            "San Miguel Alo\u00e1pam",
            "Concepci\u00f3n P\u00e1palo",
            "San Jos\u00e9 del Pe\u00f1asco",
            "Santiago Ixcuintepec",
            "Santo Domingo Ingenio",
            "San Juan Diuxi",
            "San Mateo Pi\u00f1as",
            "Santa In\u00e9s de Zaragoza",
            "San Sim\u00f3n Zahuatl\u00e1n",
            "Ayotzintepec",
            "Sitio de Xitlapehua",
            "San Miguel del Puerto",
            "San Jos\u00e9 Chiltepec",
            "Santa Catarina Ticu\u00e1",
            "Villa D\u00edaz Ordaz",
            "Santiago Matatl\u00e1n",
            "San Agust\u00edn Loxicha",
            "Santa Catarina Yosonot\u00fa",
            "Santa In\u00e9s del Monte",
            "Santa Mar\u00eda Cortijo",
            "San Juan Bautista Jayacatl\u00e1n",
            "Santo Domingo Chihuit\u00e1n",
            "Santos Reyes Yucun\u00e1",
            "San Miguel Tequixtepec",
            "Santiago Jamiltepec",
            "San Pedro y San Pablo Teposcolula",
            "Santa Catarina Quioquitani",
            "San Jos\u00e9 del Progreso",
            "Magdalena Ocotl\u00e1n",
            "San Felipe Usila",
            "Santa Mar\u00eda Yosoy\u00faa",
            "Cuil\u00e1pam de Guerrero",
            "San Mart\u00edn Lachil\u00e1",
            "San Pedro Ixcatl\u00e1n",
            "San Andr\u00e9s Nuxi\u00f1o",
            "San Mateo Tlapiltepec",
            "San Dionisio del Mar",
            "Santo Domingo Tepuxtepec",
            "Guevea de Humboldt",
            "Santa Catarina Quian\u00e9",
            "San Lorenzo",
            "San Pedro Coxcaltepec C\u00e1ntaros",
            "San Pablo Macuiltianguis",
            "San Pedro Yaneri",
            "San Agust\u00edn de las Juntas",
            "Santa Mar\u00eda Alotepec",
            "San Raymundo Jalpan",
            "Santa Ana Tlapacoyan",
            "San Pedro M\u00e1rtir Quiechapa",
            "San Pedro Huilotepec",
            "San Francisco Logueche",
            "San Jer\u00f3nimo Taviche",
            "San Miguel Amatl\u00e1n",
            "San Agust\u00edn Chayuco",
            "Santa Mar\u00eda Atzompa",
            "Santa Catarina Zapoquila",
            "Asunci\u00f3n Tlacolulita",
            "Nazareno Etla",
            "San Pedro Pochutla",
            "San Juan Bautista Lo de Soto",
            "Santiago Niltepec",
            "San Dionisio Ocotl\u00e1n",
            "Santa Mar\u00eda Tlalixtac",
            "San Pedro Ap\u00f3stol",
            "San Miguel Soyaltepec",
            "Santiago Texcalcingo",
            "Asunci\u00f3n Ocotl\u00e1n",
            "Santiago Xanica",
            "San Miguel Chimalapa",
            "Santa Mar\u00eda Guienagati",
            "Santiago Tillo",
            "Zimatl\u00e1n de \u00c1lvarez",
            "Santo Domingo Armenta",
            "Villa de Tututepec",
            "San Pedro Comitancillo",
            "Concepci\u00f3n Buenavista",
            "Loma Bonita",
            "San Pedro Jocotipac",
            "San Agust\u00edn Tlacotepec",
            "Huautepec",
            "San Sebasti\u00e1n Tecomaxtlahuaca",
            "San Juan Evangelista Analco",
            "San Pedro Teozacoalco",
            "Santa Mar\u00eda Jalapa del Marqu\u00e9s",
            "Santa Mar\u00eda Camotl\u00e1n",
            "San Mateo Cajonos",
            "San Mart\u00edn Itunyoso",
            "Magdalena Apasco",
            "San Miguel Yotao",
            "Santa Mar\u00eda Pe\u00f1oles",
            "San Lorenzo Victoria",
            "Santiago Xiacu\u00ed",
            "Santos Reyes P\u00e1palo",
            "San Miguel Tenango",
            "La Reforma",
            "Santiago Tapextla",
            "San Juan Bautista Valle Nacional",
            "San Juan Juquila Mixes",
            "Villa de Etla",
            "San Juan Achiutla",
            "San Juan Chilateca",
            "San Jos\u00e9 Estancia Grande",
            "San Mateo Yucutindoo",
            "Santa Mar\u00eda Zaniza",
            "Mixistl\u00e1n de la Reforma",
            "San Pedro Tapanatepec",
            "San Francisco Chapulapa",
            "Santa Luc\u00eda Miahuatl\u00e1n",
            "Nuevo Zoqui\u00e1pam",
            "Villa Sola de Vega",
            "Guadalupe Etla",
            "San Miguel Ahuehuetitl\u00e1n",
            "Santa Mar\u00eda Totolapilla",
            "Villa de Zaachila",
            "San Jorge Nuchita",
            "San Andr\u00e9s Sinaxtla",
            "Santiago Suchilquitongo",
            "Asunci\u00f3n Cuyotepeji",
            "San Nicol\u00e1s",
            "Santa Mar\u00eda Tonameca",
            "San Juan Cotzoc\u00f3n",
            "Santa Mar\u00eda Huazolotitl\u00e1n",
            "San Juan Lachao",
            "Villa Tej\u00fapam de la Uni\u00f3n",
            "San Francisco Sola",
            "San Vicente Coatl\u00e1n",
            "Santa Ana Tavela",
            "San Agust\u00edn Amatengo",
            "Natividad",
            "Santiago Ayuquililla",
            "Santa Mar\u00eda Colotepec",
            "Santiago Tilantongo",
            "San Sim\u00f3n Almolongas",
            "San Juan Colorado",
            "San Pedro Jaltepetongo",
            "San Ildefonso Villa Alta",
            "Santiago Huajolotitl\u00e1n",
            "Santa Cruz Itundujia",
            "Santa Mar\u00eda Chimalapa",
            "Santa Mar\u00eda Ixcatl\u00e1n",
            "Santiago Nejapilla",
            "San Pedro Ixtlahuaca",
            "Santa Mar\u00eda Texcatitl\u00e1n",
            "San Andr\u00e9s Lagunas",
            "San Juan Lachigalla",
            "Tlalixtac de Cabrera",
            "San Miguel Tulancingo",
            "Santo Domingo de Morelos",
            "San Pablo Yaganiza",
            "Teotitl\u00e1n de Flores Mag\u00f3n",
            "Yaxe",
            "Santa Gertrudis",
            "San Miguel Quetzaltepec",
            "Santiago Tenango",
            "San Agust\u00edn Yatareni",
            "Santiago Tepetlapa",
            "Santo Domingo Tehuantepec",
            "San Pedro Juchatengo",
            "Santa Mar\u00eda Zacatepec",
            "Santa Cruz Xoxocotl\u00e1n",
            "El Espinal",
            "Santiago Nuyo\u00f3",
            "San Juan Cacahuatepec",
            "San Pedro Atoyac",
            "Coatecas Altas",
            "Asunci\u00f3n Ixtaltepec",
            "San Sebasti\u00e1n Nicananduta",
            "Trinidad Zaachila",
            "San Juan Bautista Tuxtepec",
            "Santa Mar\u00eda Jacatepec",
            "Santa Cruz Tayata",
            "Santa Mar\u00eda la Asunci\u00f3n",
            "San Vicente Nu\u00f1\u00fa",
            "San Mateo Sindihui",
            "San Mateo Etlatongo",
            "Santa Mar\u00eda Yolotepec",
            "Taniche",
            "San Mart\u00edn Peras",
            "San Pablo Villa de Mitla",
            "San Pedro Quiatoni",
            "San Sebasti\u00e1n R\u00edo Hondo",
            "San Miguel Santa Flor",
            "San Baltazar Yatzachi el Bajo",
            "Constancia del Rosario",
            "San Andr\u00e9s Teotil\u00e1lpam",
            "Reforma de Pineda",
            "Santiago Jocotepec",
            "Santa Mar\u00eda Apazco",
            "Santa Mar\u00eda Temaxcalapa",
            "Santa Catarina Mechoac\u00e1n",
            "San Pablo Huitzo",
            "San Mateo del Mar",
            "Santa Mar\u00eda Quiegolani",
            "San Francisco Lachigol\u00f3",
            "Santa Mar\u00eda Coyotepec",
            "Heroica Ciudad de Huajuapan de Le\u00f3n",
            "San Juan Mixtepec -Dto. 08 -",
            "San Francisco Tlapancingo",
            "Santa Cruz Zenzontepec",
            "Ci\u00e9nega de Zimatl\u00e1n",
            "San Francisco del Mar",
            "Magdalena Jaltepec",
            "San Miguel Coatl\u00e1n",
            "San Lorenzo Cuaunecuiltitla",
            "San Pedro Mixtepec -Dto. 26 -",
            "Heroica Ciudad de Tlaxiaco",
            "Santa Mar\u00eda Nduayaco",
            "San Mateo Nej\u00e1pam",
            "Santa Catalina Quier\u00ed",
            "Santiago Lachiguiri",
            "Santa Catarina Ixtepeji",
            "San Juan Teita",
            "Miahuatl\u00e1n de Porfirio D\u00edaz",
            "San Juan Quiahije",
            "San Pedro Jicay\u00e1n",
            "Santo Domingo Yodohino",
            "Soledad Etla",
            "San Jacinto Amilpas",
            "Santiago Huauclilla",
            "Santa Mar\u00eda Teopoxco",
            "Tanetze de Zaragoza",
            "San Pedro Cajonos",
            "Asunci\u00f3n Cacalotepec",
            "San Pedro Yucunama",
            "San Antonio de la Cal",
            "San Andr\u00e9s Ya\u00e1",
            "San Felipe Jalapa de D\u00edaz",
            "Guelatao de Ju\u00e1rez",
            "Magdalena Zahuatl\u00e1n",
            "San Miguel Mixtepec",
            "San Juan Juquila Vijanos",
            "San Antonino el Alto",
            "San Pablo Coatl\u00e1n",
            "Totontepec Villa de Morelos",
            "Santa Mar\u00eda Ecatepec",
            "San Pedro Y\u00f3lox",
            "San Pablo Etla",
            "La Pe",
            "Santa Mar\u00eda Zoquitl\u00e1n",
            "San Juan Mixtepec -Dto. 26 -",
            "San Juan Bautista Suchitepec",
            "Eloxochitl\u00e1n de Flores Mag\u00f3n",
            "Santa Mar\u00eda Jaltianguis",
            "Ayoquezco de Aldama",
            "San Juan Bautista Tlacoatzintepec",
            "San Pedro y San Pablo Tequixtepec",
            "Santo Domingo Tonaltepec",
            "Santo Domingo Nuxa\u00e1",
            "San Andr\u00e9s Dinicuiti",
            "San Pablo Huixtepec",
            "Mazatl\u00e1n Villa de Flores",
            "San Andr\u00e9s Tepetlapa",
            "Santa Mar\u00eda Temaxcaltepec",
            "San Juan Guelav\u00eda",
            "San Jer\u00f3nimo Sosola",
            "Santa Mar\u00eda P\u00e1palo",
            "Santa Cruz Tacahua",
            "Magdalena Teitipac",
            "San Francisco Ixhuat\u00e1n",
            "Santo Domingo Roayaga",
            "San Juan \u00d1um\u00ed",
            "San Juan Taba\u00e1",
            "Santa Mar\u00eda Yalina",
            "Santiago Atitl\u00e1n",
            "Cuyamecalco Villa de Zaragoza",
            "Santa Mar\u00eda Petapa",
            "San Pedro Totol\u00e1pam",
            "Santo Tom\u00e1s Tamazulapan",
            "Santo Domingo Tlatay\u00e1pam",
            "San Mart\u00edn Toxpalan",
            "San Bartolom\u00e9 Ayautla",
            "San Baltazar Chichic\u00e1pam",
            "San Bartolom\u00e9 Loxicha",
            "San Juan Coatz\u00f3spam",
            "Candelaria Loxicha",
            "San Jer\u00f3nimo Coatl\u00e1n",
            "San Jos\u00e9 Lachiguiri",
            "Santa Mar\u00eda Chacho\u00e1pam",
            "Teotitl\u00e1n del Valle",
            "Fresnillo de Trujano",
            "Valerio Trujano",
            "Tlacotepec Plumas",
            "Yogana",
            "Asunci\u00f3n Nochixtl\u00e1n",
            "Villa de Tamazul\u00e1pam del Progreso",
            "Magdalena Yodocono de Porfirio D\u00edaz",
            "Santiago Nacaltepec",
            "San Andr\u00e9s Ixtlahuaca",
            "San Pedro Amuzgos",
            "San Miguel Huautla",
            "San Pedro Huamelula",
            "\u00c1nimas Trujano",
            "San Bartolo Soyaltepec",
            "San Antonino Monte Verde",
            "San Juan Teposcolula",
            "Putla Villa de Guerrero",
            "Santiago Yosond\u00faa",
            "Santa Mar\u00eda Xadani",
            "San Pablo Tijaltepec",
            "Magdalena Tequisistl\u00e1n",
            "Santa Catarina Juquila",
            "San Sebasti\u00e1n Ixcapa",
            "Pinotepa de Don Luis",
            "San Francisco Huehuetl\u00e1n",
            "San Juan Bautista Tlachichilco",
            "San Antonio Sinicahua",
            "San Juan Yatzona",
            "San Lorenzo Albarradas",
            "San Juan Atepec",
            "San Lucas Zoqui\u00e1pam",
            "San Pedro Taviche",
            "Santiago Tlazoyaltepec",
            "Santa Luc\u00eda Ocotl\u00e1n",
            "Santiago Laollaga",
            "San Andr\u00e9s Cabecera Nueva",
            "Santa Ana Ateixtlahuaca",
            "San Jer\u00f3nimo Tec\u00f3atl",
            "San Juan Yucuita",
            "Santa Catarina Cuixtla",
            "Santa Mar\u00eda Lachix\u00edo",
            "San Luis Amatl\u00e1n",
            "Santa Ana Yareni",
            "San Pedro Teutila",
            "San Agust\u00edn Etla",
            "Tezoatl\u00e1n de Segura y Luna",
            "Santa Mar\u00eda Yaves\u00eda",
            "Chahuites",
            "San Pedro el Alto",
            "Calihual\u00e1",
            "San Mateo Pe\u00f1asco",
            "Santa Cruz Papalutla",
            "Zapotitl\u00e1n Palmas",
            "San Miguel Tilqui\u00e1pam",
            "San Juan Mazatl\u00e1n",
            "Santiago Cho\u00e1pam",
            "San Francisco Chind\u00faa",
            "San Jos\u00e9 Tenango",
            "San Miguel el Grande",
            "Heroica Villa de San Blas Atempa",
            "Villa de Santiago Chazumba",
            "Santo Domingo Zanatepec",
            "San Mateo Yoloxochitl\u00e1n",
            "Santa Mar\u00eda Nativitas",
            "Santa Catarina Loxicha",
            "Santa Mar\u00eda Guelac\u00e9",
            "Villa Hidalgo Yal\u00e1lag",
            "Magdalena Tlacotepec",
            "Santa Mar\u00eda Tecomavaca",
            "Silacayo\u00e1pam",
            "Santo Domingo Ozolotepec",
            "San Juan Ihualtepec",
            "San Juan Cieneguilla",
            "San Andr\u00e9s Paxtl\u00e1n",
            "San Sebasti\u00e1n Tutla",
            "Santo Domingo Ixcatl\u00e1n",
            "Santo Tom\u00e1s Mazaltepec",
            "Santo Tom\u00e1s Ocotepec",
            "San Crist\u00f3bal Amoltepec",
            "Santo Domingo Xagac\u00eda",
            "San Miguel Amatitl\u00e1n",
            "El Barrio de la Soledad",
            "Santiago Tamazola",
            "Mariscala de Ju\u00e1rez",
            "Santa Ana Zegache",
            "Ocotl\u00e1n de Morelos",
            "San Nicol\u00e1s Hidalgo",
            "Santiago Cacaloxtepec",
            "Santa Cruz de Bravo",
            "Mesones Hidalgo",
            "Santiago Ap\u00f3stol",
            "Cosolapa",
            "Santiago Ihuitl\u00e1n Plumas",
            "San Miguel del R\u00edo",
            "San Miguel Tlacotepec",
            "Santo Domingo Albarradas",
            "Tlacolula de Matamoros",
            "San Bartolom\u00e9 Zoogocho",
            "San Mart\u00edn de los Cansecos",
            "San Francisco Cahuacu\u00e1"
        ]
    },
    {
        "Estado": "Puebla",
        "Ciudad": [
            "Chiautzingo",
            "Esperanza",
            "Tepeojuma",
            "Zoquitl\u00e1n",
            "Chila",
            "San Salvador Huixcolotla",
            "Teopantl\u00e1n",
            "Huaquechula",
            "Santa Isabel Cholula",
            "Tetela de Ocampo",
            "Cohuecan",
            "Tlachichuca",
            "Axutla",
            "Tlacuilotepec",
            "Nicol\u00e1s Bravo",
            "Tlatlauquitepec",
            "Pahuatl\u00e1n",
            "San Mart\u00edn Texmelucan",
            "San Jos\u00e9 Chiapa",
            "Xochitl\u00e1n Todos Santos",
            "Juan Galindo",
            "Tepeaca",
            "San Sebasti\u00e1n Tlacotepec",
            "Cuautempan",
            "Pantepec",
            "Huejotzingo",
            "Huitziltepec",
            "San Salvador el Seco",
            "San Andr\u00e9s Cholula",
            "Amixtl\u00e1n",
            "Chignahuapan",
            "Cuautinch\u00e1n",
            "Tepexco",
            "Tianguismanalco",
            "Zihuateutla",
            "Eloxochitl\u00e1n",
            "Xayacatl\u00e1n de Bravo",
            "Piaxtla",
            "Huehuetl\u00e1n el Chico",
            "Ixtepec",
            "Chiconcuautla",
            "Tlaxco",
            "Tlaola",
            "Tecali de Herrera",
            "Nopalucan",
            "Jalpan",
            "Ocotepec",
            "San Nicol\u00e1s Buenos Aires",
            "San Salvador el Verde",
            "Coyomeapan",
            "Santo Tom\u00e1s Hueyotlipan",
            "Tepeyahualco de Cuauht\u00e9moc",
            "Zoquiapan",
            "Ixtacamaxtitl\u00e1n",
            "Albino Zertuche",
            "San Juan Atzompa",
            "Xochiltepec",
            "Ahuatl\u00e1n",
            "San Felipe Tepatl\u00e1n",
            "Ocoyucan",
            "San Pablo Anicano",
            "Altepexi",
            "Tepexi de Rodr\u00edguez",
            "Xochitl\u00e1n de Vicente Su\u00e1rez",
            "Coronango",
            "Teotlalco",
            "Zautla",
            "Tlahuapan",
            "Hueytamalco",
            "Quimixtl\u00e1n",
            "Jonotla",
            "Santa In\u00e9s Ahuatempan",
            "Chiautla",
            "Chalchicomula de Sesma",
            "Atzala",
            "Huitzilan de Serd\u00e1n",
            "Caltepec",
            "Hueytlalpan",
            "Venustiano Carranza",
            "Coatzingo",
            "San Mart\u00edn Totoltepec",
            "Tepanco de L\u00f3pez",
            "Aljojuca",
            "Santa Catarina Tlaltempan",
            "Mixtla",
            "Cuayuca de Andrade",
            "Aquixtla",
            "Atlixco",
            "Santiago Miahuatl\u00e1n",
            "Tuzamapan de Galeana",
            "Francisco Z. Mena",
            "Atoyatempan",
            "Acateno",
            "Oriental",
            "Zaragoza",
            "San Jer\u00f3nimo Xayacatl\u00e1n",
            "Zacapala",
            "Tepango de Rodr\u00edguez",
            "Nealtican",
            "General Felipe \u00c1ngeles",
            "Huatlatlauca",
            "Zapotitl\u00e1n",
            "Vicente Guerrero",
            "Tecamachalco",
            "Ixcaquixtla",
            "Coxcatl\u00e1n",
            "Xiutetelco",
            "Yehualtepec",
            "Tehuac\u00e1n",
            "Xochiapulco",
            "Teteles de \u00c1vila Castillo",
            "Quecholac",
            "Epatl\u00e1n",
            "San Pedro Cholula",
            "Huehuetla",
            "Tepeyahualco",
            "Yaon\u00e1huac",
            "Totoltepec de Guerrero",
            "Ajalpan",
            "Tlapacoya",
            "Cohetzala",
            "Puebla",
            "Tlacotepec de Benito Ju\u00e1rez",
            "Atlequizayan",
            "Petlalcingo",
            "Zapotitl\u00e1n de M\u00e9ndez",
            "Tlapanal\u00e1",
            "Acatzingo",
            "Zinacatepec",
            "Tlaltenango",
            "Atzitzihuac\u00e1n",
            "Cuetzalan del Progreso",
            "San Juan Atenco",
            "Zongozotla",
            "Chilchotla",
            "San Diego la Mesa Tochimiltzingo",
            "Huauchinango",
            "Tepetzintla",
            "San Nicol\u00e1s de los Ranchos",
            "Zacatl\u00e1n",
            "Xicotl\u00e1n",
            "Lafragua",
            "Ca\u00f1ada Morelos",
            "San Jer\u00f3nimo Tecuanipan",
            "Juan N. M\u00e9ndez",
            "Chignautla",
            "Juan C. Bonilla",
            "Iz\u00facar de Matamoros",
            "Chichiquila",
            "Naupan",
            "Huehuetl\u00e1n el Grande",
            "Chapulco",
            "Chinantla",
            "Cuyoaco",
            "Amozoc",
            "San Jos\u00e9 Miahuatl\u00e1n",
            "Guadalupe Victoria",
            "Zacapoaxtla",
            "Ahuehuetitla",
            "Tochtepec",
            "Tulcingo",
            "Guadalupe",
            "Molcaxac",
            "Ayotoxco de Guerrero",
            "San Mat\u00edas Tlalancaleca",
            "Camocuautla",
            "Coyotepec",
            "Hueyapan",
            "Nauzontla",
            "Soltepec",
            "Ahuacatl\u00e1n",
            "San Felipe Teotlalcingo",
            "Tilapa",
            "Chigmecatitl\u00e1n",
            "Acajete",
            "Mazapiltepec de Ju\u00e1rez",
            "Coatepec",
            "Acatl\u00e1n",
            "Honey",
            "Atzitzintla",
            "Acteopan",
            "Xicotepec",
            "Libres",
            "Jopala",
            "Hermenegildo Galeana",
            "Ahuazotepec",
            "Olintla",
            "Tehuitzingo",
            "San Miguel Ixitl\u00e1n",
            "Calpan",
            "La Magdalena Tlatlauquitepec",
            "Palmar de Bravo",
            "Caxhuacan",
            "Tecomatl\u00e1n",
            "San Gregorio Atzompa",
            "Tenampulco",
            "Atempan",
            "Rafael Lara Grajales",
            "Jolalpan",
            "Tzicatlacoyan",
            "Tochimilco",
            "San Antonio Ca\u00f1ada",
            "Tepatlaxco de Hidalgo",
            "San Miguel Xoxtla",
            "Cuapiaxtla de Madero",
            "Cuautlancingo",
            "Tlanepantla",
            "San Gabriel Chilac",
            "Chila de la Sal",
            "Chietla",
            "Tepemaxalco",
            "Domingo Arenas",
            "Atexcal",
            "Teziutl\u00e1n",
            "Ixcamilpa de Guerrero",
            "San Pedro Yeloixtlahuaca",
            "Los Reyes de Ju\u00e1rez"
        ]
    },
    {
        "Estado": "Quer\u00e9taro",
        "Ciudad": [
            "El Marqu\u00e9s",
            "Arroyo Seco",
            "Quer\u00e9taro",
            "Landa de Matamoros",
            "Pe\u00f1amiller",
            "Tequisquiapan",
            "Amealco de Bonfil",
            "Col\u00f3n",
            "Ezequiel Montes",
            "Pedro Escobedo",
            "Tolim\u00e1n",
            "Pinal de Amoles",
            "San Joaqu\u00edn",
            "San Juan del R\u00edo",
            "Huimilpan",
            "Corregidora",
            "Cadereyta de Montes",
            "Jalpan de Serra"
        ]
    },
    {
        "Estado": "Quintana_Roo",
        "Ciudad": [
            "Jos\u00e9 Mar\u00eda Morelos",
            "Bacalar",
            "Oth\u00f3n P. Blanco",
            "Benito Ju\u00e1rez",
            "Solidaridad",
            "Tulum",
            "Isla Mujeres",
            "Felipe Carrillo Puerto",
            "L\u00e1zaro C\u00e1rdenas",
            "Cozumel",
            "Puerto Morelos"
        ]
    },
    {
        "Estado": "San_Luis_Potos\u00ed",
        "Ciudad": [
            "Xilitla",
            "Santa Mar\u00eda del R\u00edo",
            "Santo Domingo",
            "C\u00e1rdenas",
            "San Vicente Tancuayalab",
            "Moctezuma",
            "San Luis Potos\u00ed",
            "Villa Hidalgo",
            "San Ciro de Acosta",
            "Ebano",
            "San Nicol\u00e1s Tolentino",
            "Tancanhuitz",
            "Ciudad del Ma\u00edz",
            "Villa de Arista",
            "Villa de Pozos",
            "Villa de la Paz",
            "Ciudad Fern\u00e1ndez",
            "Ciudad Valles",
            "Axtla de Terrazas",
            "Villa de Ramos",
            "Guadalc\u00e1zar",
            "Salinas",
            "Tamu\u00edn",
            "Villa de Reyes",
            "Cerro de San Pedro",
            "Cerritos",
            "Ahualulco del Sonido 13",
            "San Antonio",
            "Cedral",
            "Villa de Guadalupe",
            "Catorce",
            "Tanqui\u00e1n de Escobedo",
            "Venado",
            "Ray\u00f3n",
            "Tierra Nueva",
            "Armadillo de los Infante",
            "Huehuetl\u00e1n",
            "Matehuala",
            "El Naranjo",
            "Villa de Arriaga",
            "Mexquitic de Carmona",
            "Matlapa",
            "Tanlaj\u00e1s",
            "San Mart\u00edn Chalchicuautla",
            "Soledad de Graciano S\u00e1nchez",
            "Charcas",
            "Alaquines",
            "Tamasopo",
            "Tampamol\u00f3n Corona",
            "Tampac\u00e1n",
            "Rioverde",
            "Vanegas",
            "Villa Ju\u00e1rez",
            "Zaragoza",
            "Aquism\u00f3n",
            "Lagunillas",
            "Santa Catarina",
            "Coxcatl\u00e1n",
            "Tamazunchale"
        ]
    },
    {
        "Estado": "Sinaloa",
        "Ciudad": [
            "Badiraguato",
            "Eldorado",
            "Navolato",
            "Guasave",
            "Concordia",
            "San Ignacio",
            "Choix",
            "Angostura",
            "Juan Jos\u00e9 R\u00edos",
            "Rosario",
            "Cosal\u00e1",
            "Sinaloa",
            "Ahome",
            "Mazatl\u00e1n",
            "El Fuerte",
            "Mocorito",
            "Escuinapa",
            "Salvador Alvarado",
            "Culiac\u00e1n",
            "Elota"
        ]
    },
    {
        "Estado": "Sonora",
        "Ciudad": [
            "Pitiquito",
            "Guaymas",
            "Ban\u00e1michi",
            "Hu\u00e9pac",
            "Moctezuma",
            "Agua Prieta",
            "Hu\u00e1sabas",
            "Cananea",
            "Villa Hidalgo",
            "San Felipe de Jes\u00fas",
            "Benito Ju\u00e1rez",
            "Etchojoa",
            "Arizpe",
            "Bacanora",
            "Naco",
            "Santa Cruz",
            "Benjam\u00edn Hill",
            "Altar",
            "Trincheras",
            "Aconchi",
            "Y\u00e9cora",
            "Bacad\u00e9huachi",
            "Suaqui Grande",
            "Santa Ana",
            "Bacerac",
            "Ures",
            "Puerto Pe\u00f1asco",
            "San Miguel de Horcasitas",
            "Caborca",
            "S\u00e1ric",
            "Huachinera",
            "San Javier",
            "Magdalena",
            "Rosario",
            "Cucurpe",
            "Oquitoa",
            "San Luis R\u00edo Colorado",
            "General Plutarco El\u00edas Calles",
            "Huatabampo",
            "Navojoa",
            "Divisaderos",
            "Bacoachi",
            "Sahuaripa",
            "San Pedro de la Cueva",
            "Tepache",
            "Opodepe",
            "Ray\u00f3n",
            "B\u00e1cum",
            "N\u00e1cori Chico",
            "Cajeme",
            "Villa Pesqueira",
            "Nogales",
            "La Colorada",
            "Cumpas",
            "Quiriego",
            "Empalme",
            "Soyopa",
            "Atil",
            "Granados",
            "Bavispe",
            "Tubutama",
            "Arivechi",
            "Nacozari de Garc\u00eda",
            "Bavi\u00e1cora",
            "Hermosillo",
            "\u00d3navas",
            "Imuris",
            "Mazat\u00e1n",
            "Carb\u00f3",
            "Fronteras",
            "San Ignacio R\u00edo Muerto",
            "\u00c1lamos"
        ]
    },
    {
        "Estado": "Tabasco",
        "Ciudad": [
            "C\u00e1rdenas",
            "Teapa",
            "Emiliano Zapata",
            "Centla",
            "Tacotalpa",
            "Centro",
            "Tenosique",
            "Jonuta",
            "Nacajuca",
            "Huimanguillo",
            "Jalpa de M\u00e9ndez",
            "Comalcalco",
            "Para\u00edso",
            "Macuspana",
            "Jalapa",
            "Cunduac\u00e1n",
            "Balanc\u00e1n"
        ]
    },
    {
        "Estado": "Tamaulipas",
        "Ciudad": [
            "Villagr\u00e1n",
            "Nuevo Morelos",
            "Valle Hermoso",
            "Nuevo Laredo",
            "Reynosa",
            "Matamoros",
            "Victoria",
            "San Nicol\u00e1s",
            "Antiguo Morelos",
            "Miquihuana",
            "Gonz\u00e1lez",
            "San Fernando",
            "Miguel Alem\u00e1n",
            "Tula",
            "Ocampo",
            "Burgos",
            "Guerrero",
            "Hidalgo",
            "Camargo",
            "Altamira",
            "Ciudad Madero",
            "Soto la Marina",
            "El Mante",
            "Abasolo",
            "R\u00edo Bravo",
            "Bustamante",
            "Jaumave",
            "Gustavo D\u00edaz Ordaz",
            "Aldama",
            "Palmillas",
            "Llera",
            "M\u00e9ndez",
            "G\u00f3mez Far\u00edas",
            "Tampico",
            "Xicot\u00e9ncatl",
            "Padilla",
            "Mainero",
            "San Carlos",
            "Jim\u00e9nez",
            "G\u00fc\u00e9mez",
            "Cruillas",
            "Mier",
            "Casas"
        ]
    },
    {
        "Estado": "Tlaxcala",
        "Ciudad": [
            "Santa Catarina Ayometla",
            "San Lorenzo Axocomanitla",
            "Apizaco",
            "Ixtacuixtla de Mariano Matamoros",
            "San Jos\u00e9 Teacalco",
            "La Magdalena Tlaltelulco",
            "Panotla",
            "Benito Ju\u00e1rez",
            "Tzompantepec",
            "Tlaxco",
            "Huamantla",
            "L\u00e1zaro C\u00e1rdenas",
            "Tenancingo",
            "Atlangatepec",
            "Ixtenco",
            "Xaloztoc",
            "Terrenate",
            "Espa\u00f1ita",
            "Apetatitl\u00e1n de Antonio Carvajal",
            "Yauhquemehcan",
            "Cuaxomulco",
            "Tepetitla de Lardiz\u00e1bal",
            "Tetlatlahuca",
            "Zacatelco",
            "San Juan Huactzinco",
            "Teolocholco",
            "El Carmen Tequexquitla",
            "Papalotla de Xicoht\u00e9ncatl",
            "San Lucas Tecopilco",
            "Contla de Juan Cuamatzi",
            "Hueyotlipan",
            "Tocatl\u00e1n",
            "Tlaxcala",
            "Ziltlalt\u00e9pec de Trinidad S\u00e1nchez Santos",
            "Nat\u00edvitas",
            "Atltzayanca",
            "Calpulalpan",
            "Cuapiaxtla",
            "Santa Cruz Tlaxcala",
            "San Dami\u00e1n Tex\u00f3loc",
            "Chiautempan",
            "San Pablo del Monte",
            "Totolac",
            "Nanacamilpa de Mariano Arista",
            "Tetla de la Solidaridad",
            "Emiliano Zapata",
            "Santa Cruz Quilehtla",
            "Santa Isabel Xiloxoxtla",
            "Sanct\u00f3rum de L\u00e1zaro C\u00e1rdenas",
            "Santa Ana Nopalucan",
            "Tepeyanco",
            "Amaxac de Guerrero",
            "Acuamanala de Miguel Hidalgo",
            "Xicohtzinco",
            "Mazatecochco de Jos\u00e9 Mar\u00eda Morelos",
            "San Francisco Tetlanohcan",
            "Mu\u00f1oz de Domingo Arenas",
            "San Jer\u00f3nimo Zacualpan",
            "Xaltocan",
            "Santa Apolonia Teacalco"
        ]
    },
    {
        "Estado": "Veracruz_de_Ignacio_de_la_Llave",
        "Ciudad": [
            "Xalapa",
            "Soconusco",
            "Xoxocotla",
            "Tlalnelhuayocan",
            "Tezonapa",
            "Benito Ju\u00e1rez",
            "Ixhuac\u00e1n de los Reyes",
            "Yecuatla",
            "Hidalgotitl\u00e1n",
            "Tenampa",
            "Nautla",
            "Cerro Azul",
            "Chacaltianguis",
            "Coxquihui",
            "Tehuipango",
            "Playa Vicente",
            "Tuxpan",
            "Las Choapas",
            "Acula",
            "Cosautl\u00e1n de Carvajal",
            "Misantla",
            "Atoyac",
            "Tepatlaxco",
            "Ursulo Galv\u00e1n",
            "Ixmatlahuacan",
            "Hueyapan de Ocampo",
            "Zozocolco de Hidalgo",
            "Omealca",
            "Ayahualulco",
            "Tihuatl\u00e1n",
            "Rafael Delgado",
            "Ilamatl\u00e1n",
            "Ixhuatl\u00e1n de Madero",
            "Actopan",
            "Medell\u00edn de Bravo",
            "Coyutla",
            "San Rafael",
            "Tlalixcoyan",
            "Jilotepec",
            "Guti\u00e9rrez Zamora",
            "Los Reyes",
            "Rafael Lucio",
            "Huiloapan de Cuauht\u00e9moc",
            "Teocelo",
            "Ixhuatl\u00e1n del Caf\u00e9",
            "P\u00e1nuco",
            "Chocam\u00e1n",
            "Paso del Macho",
            "Cuitl\u00e1huac",
            "Jos\u00e9 Azueta",
            "Naranjal",
            "Jalacingo",
            "R\u00edo Blanco",
            "Altotonga",
            "Tierra Blanca",
            "Alvarado",
            "Coatzacoalcos",
            "Soledad de Doblado",
            "Calcahualco",
            "Manlio Fabio Altamirano",
            "Tepetl\u00e1n",
            "Chinameca",
            "Camerino Z. Mendoza",
            "Tuxtilla",
            "Chalma",
            "Filomeno Mata",
            "Alto Lucero de Guti\u00e9rrez Barrios",
            "Tampico Alto",
            "Aquila",
            "Mecayapan",
            "Acayucan",
            "Landero y Coss",
            "Cuichapa",
            "Oluta",
            "Xico",
            "Magdalena",
            "Orizaba",
            "Uxpanapa",
            "Camar\u00f3n de Tejeda",
            "Atzacan",
            "Acultzingo",
            "Veracruz",
            "Texhuac\u00e1n",
            "Sayula de Alem\u00e1n",
            "Coatzintla",
            "Angel R. Cabada",
            "Amatl\u00e1n de los Reyes",
            "Texcatepec",
            "Tenochtitl\u00e1n",
            "Boca del R\u00edo",
            "Tlaltetela",
            "Atlahuilco",
            "Paso de Ovejas",
            "Mariano Escobedo",
            "Coahuitl\u00e1n",
            "Comapa",
            "Moloac\u00e1n",
            "Jes\u00fas Carranza",
            "Carrillo Puerto",
            "Puente Nacional",
            "La Antigua",
            "Isla",
            "Chumatl\u00e1n",
            "Zaragoza",
            "Maltrata",
            "Tlacotepec de Mej\u00eda",
            "Alpatl\u00e1huac",
            "Jamapa",
            "Totutla",
            "Tlapacoyan",
            "Ixhuatl\u00e1n del Sureste",
            "Tantima",
            "Tecolutla",
            "Zongolica",
            "Amatitl\u00e1n",
            "Naolinco",
            "Coacoatzintla",
            "Chiconquiaco",
            "San Andr\u00e9s Tuxtla",
            "Tlilapan",
            "La Perla",
            "Cosoleacaque",
            "Tlacolulan",
            "Ozuluama de Mascare\u00f1as",
            "Ixtaczoquitl\u00e1n",
            "Lerdo de Tejada",
            "Cazones de Herrera",
            "Atzalan",
            "Tatatila",
            "Juan Rodr\u00edguez Clara",
            "Soledad Atzompa",
            "Minatitl\u00e1n",
            "C\u00f3rdoba",
            "Tancoco",
            "Astacinga",
            "Mixtla de Altamirano",
            "J\u00e1ltipan",
            "Naranjos Amatl\u00e1n",
            "\u00c1lamo Temapache",
            "Perote",
            "Emiliano Zapata",
            "Jalcomulco",
            "Miahuatl\u00e1n",
            "Tlacotalpan",
            "Nogales",
            "Tepetzintla",
            "Zacualpan",
            "Mecatl\u00e1n",
            "Tlaquilpa",
            "Zontecomatl\u00e1n de L\u00f3pez y Fuentes",
            "Sochiapa",
            "San Andr\u00e9s Tenejapan",
            "Villa Aldama",
            "Chicontepec",
            "Santiago Sochiapan",
            "Agua Dulce",
            "Colipa",
            "Pajapan",
            "Coetzala",
            "Soteapan",
            "Las Vigas de Ram\u00edrez",
            "Plat\u00f3n S\u00e1nchez",
            "Huayacocotla",
            "Carlos A. Carrillo",
            "Las Minas",
            "Oteapan",
            "Huatusco",
            "Banderilla",
            "Citlalt\u00e9petl",
            "Catemaco",
            "San Juan Evangelista",
            "Texistepec",
            "Pueblo Viejo",
            "Ixhuatlancillo",
            "Santiago Tuxtla",
            "Apazapan",
            "Vega de Alatorre",
            "Tatahuicapan de Ju\u00e1rez",
            "Poza Rica de Hidalgo",
            "Ignacio de la Llave",
            "Acajete",
            "Cotaxtla",
            "Tres Valles",
            "Cosamaloapan de Carpio",
            "Coatepec",
            "Acatl\u00e1n",
            "Tonay\u00e1n",
            "Espinal",
            "Ixcatepec",
            "Tequila",
            "Nanchital de L\u00e1zaro C\u00e1rdenas del R\u00edo",
            "Mart\u00ednez de la Torre",
            "Juchique de Ferrer",
            "Castillo de Teayo",
            "Saltabarranca",
            "Chontla",
            "Tempoal",
            "Tlachichilco",
            "Tamal\u00edn",
            "Tamiahua",
            "Fort\u00edn",
            "Papantla",
            "Otatitl\u00e1n",
            "El Higo",
            "Coscomatepec",
            "Chiconamel",
            "Tlacojalpan",
            "Chinampa de Gorostiza",
            "Yanga",
            "Zentla",
            "Tantoyuca",
            "Tomatl\u00e1n"
        ]
    },
    {
        "Estado": "Yucat\u00e1n",
        "Ciudad": [
            "Um\u00e1n",
            "Dzilam Gonz\u00e1lez",
            "Abal\u00e1",
            "Bokob\u00e1",
            "Man\u00ed",
            "Tetiz",
            "Celest\u00fan",
            "Tizim\u00edn",
            "Kantunil",
            "Telchac Puerto",
            "Panab\u00e1",
            "Tunk\u00e1s",
            "Dzilam de Bravo",
            "Telchac Pueblo",
            "Sudzal",
            "Motul",
            "Sucil\u00e1",
            "Tixkokob",
            "Quintana Roo",
            "Chichimil\u00e1",
            "Tinum",
            "San Felipe",
            "Espita",
            "Sanahcat",
            "Chochol\u00e1",
            "Oxkutzcab",
            "Chankom",
            "Tixcacalcupul",
            "Kinchil",
            "Yaxcab\u00e1",
            "Tahdzi\u00fa",
            "Santa Elena",
            "Cuzam\u00e1",
            "Cansahcab",
            "Halach\u00f3",
            "Peto",
            "Chikindzonot",
            "Samahil",
            "Calotmul",
            "Cacalch\u00e9n",
            "Chemax",
            "Temoz\u00f3n",
            "Chicxulub Pueblo",
            "Progreso",
            "Buctzotz",
            "Kaua",
            "R\u00edo Lagartos",
            "Sinanch\u00e9",
            "Suma",
            "Cuncunul",
            "Chacsink\u00edn",
            "Temax",
            "Akil",
            "Maxcan\u00fa",
            "Hom\u00fan",
            "Sotuta",
            "Tecoh",
            "Tekax",
            "Hunucm\u00e1",
            "Hocab\u00e1",
            "Hoct\u00fan",
            "Sey\u00e9",
            "Dzemul",
            "Teya",
            "M\u00e9rida",
            "Ixil",
            "Tekit",
            "Mococh\u00e1",
            "Dzoncauich",
            "Yoba\u00edn",
            "Muna",
            "Cenotillo",
            "Izamal",
            "Valladolid",
            "Chapab",
            "Mama",
            "Chumayel",
            "Opich\u00e9n",
            "Tekom",
            "Xocchel",
            "Kopom\u00e1",
            "Dzidzant\u00fan",
            "Tixm\u00e9huac",
            "Sacalum",
            "Muxupip",
            "Ticul",
            "Kanas\u00edn",
            "Uayma",
            "Dzan",
            "Mayap\u00e1n",
            "Tekant\u00f3",
            "Timucuy",
            "Dzit\u00e1s",
            "Acanceh",
            "Uc\u00fa",
            "Teabo",
            "Conkal",
            "Tzucacab",
            "Tekal de Venegas",
            "Tixp\u00e9hual",
            "Yaxkukul",
            "Cantamayec",
            "Tahmek",
            "Tepak\u00e1n",
            "Huh\u00ed",
            "Baca"
        ]
    },
    {
        "Estado": "Zacatecas",
        "Ciudad": [
            "Apozol",
            "Guadalupe",
            "Santa Mar\u00eda de la Paz",
            "Villa Gonz\u00e1lez Ortega",
            "Monte Escobedo",
            "Villa Hidalgo",
            "El Plateado de Joaqu\u00edn Amaro",
            "Tabasco",
            "Ca\u00f1itas de Felipe Pescador",
            "Benito Ju\u00e1rez",
            "Valpara\u00edso",
            "Atolinga",
            "Jim\u00e9nez del Teul",
            "Mazapil",
            "Momax",
            "Pinos",
            "Luis Moya",
            "Chalchihuites",
            "Concepci\u00f3n del Oro",
            "Sombrerete",
            "Tepetongo",
            "Vetagrande",
            "Noria de \u00c1ngeles",
            "Villa Garc\u00eda",
            "Loreto",
            "Huanusco",
            "Ojocaliente",
            "Tepechitl\u00e1n",
            "Villanueva",
            "General Francisco R. Murgu\u00eda",
            "General Enrique Estrada",
            "Trancoso",
            "Moyahua de Estrada",
            "Melchor Ocampo",
            "Nochistl\u00e1n de Mej\u00eda",
            "Juan Aldama",
            "Apulco",
            "General P\u00e1nfilo Natera",
            "Genaro Codina",
            "Zacatecas",
            "Morelos",
            "El Salvador",
            "Fresnillo",
            "Mezquital del Oro",
            "P\u00e1nuco",
            "Trinidad Garc\u00eda de la Cadena",
            "Cuauht\u00e9moc",
            "Sain Alto",
            "Jerez",
            "Jalpa",
            "Calera",
            "R\u00edo Grande",
            "Villa de Cos",
            "Tlaltenango de S\u00e1nchez Rom\u00e1n",
            "Susticac\u00e1n",
            "Miguel Auza",
            "Juchipila",
            "Te\u00fal de Gonz\u00e1lez Ortega"
        ]
    }
]